### ISSUE TITLE
Some Error Need Help

### ISSUE THREAD

**Issue by xtzd** [moon-hotel/TransformerCouplet#1]
Hi, when I am using your train/test code, some errors came out:
$python couplet.py

Traceback (most recent call last):
  File "/home/jed/projects/TransformerCouplet/couplet.py", line 74, in <module>
    results = do_couplet(srcs, config)
  File "/home/jed/projects/TransformerCouplet/couplet.py", line 58, in do_couplet
    r = couplet(couplet_model, src, data_loader, config)
  File "/home/jed/projects/TransformerCouplet/couplet.py", line 35, in couplet
    tgt_tokens = greedy_decode(model, src, max_len=num_tokens + 5,
  File "/home/jed/projects/TransformerCouplet/couplet.py", line 16, in greedy_decode
    out = model.decoder(ys, memory, tgt_mask)  # [tgt_len,tgt_vocab_size]
  File "/home/jed/projects/TransformerCouplet/model/CoupletModel.py", line 57, in decoder
    tgt_embed = self.tgt_token_embedding(tgt)  # [tgt_len, batch_size, embed_dim]
  File "/home/jed/miniconda3/envs/common/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CoupletModel' object has no attribute 'tgt_token_embedding'

**Comment by xiaopanchen** [comment]
上联：晚风摇树树还挺
 AI：早悬贴贴拱贴贴
下联：晨露润花花更红
=======
上联：忽忽几晨昏，离别间之，疾病间之，不及终年同静好
 AI：茕闲四神尊王，人寮谨留盯谈宙贴闱缕
下联：茕茕小儿女，孱羸若此，娇憨若此，更烦二老费精神
=======
上联：风声、雨声、读书声，声声入耳
 AI：山邹须蜿、逻谐春托部关替轨
下联：家事、国事、天下事，事事关心
=======
效果并不是特别好。什么原因呢？直接使用你原有的模型和参数

**Comment by iissy** [comment]
> # 上联：晚风摇树树还挺
> AI：早悬贴贴拱贴贴
> 下联：晨露润花花更红
> # 上联：忽忽几晨昏，离别间之，疾病间之，不及终年同静好
> AI：茕闲四神尊王，人寮谨留盯谈宙贴闱缕
> 下联：茕茕小儿女，孱羸若此，娇憨若此，更烦二老费精神
> # 上联：风声、雨声、读书声，声声入耳
> AI：山邹须蜿、逻谐春托部关替轨
> 下联：家事、国事、天下事，事事关心
> 效果并不是特别好。什么原因呢？直接使用你原有的模型和参数

有跑够100轮吗，我跑几轮，效果很不好。
